#if !canImport(ObjectiveC)
import XCTest

extension TabulaKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TabulaKitTests = [
        ("testTabula", testTabula),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TabulaKitTests.__allTests__TabulaKitTests),
    ]
}
#endif
